// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJo6RFfvb0yLQ9O7b7hMURFw3xXVusZ-w',
    appId: '1:651913327335:web:d4098b3140c4c3decaa842',
    messagingSenderId: '651913327335',
    projectId: 'eazy-order-fcb5b',
    authDomain: 'eazy-order-fcb5b.firebaseapp.com',
    storageBucket: 'eazy-order-fcb5b.firebasestorage.app',
    measurementId: 'G-YY6S94CKJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNC9-0rYC-Al5s2Z7XuhjxPy6anSTcAM',
    appId: '1:651913327335:android:5a4b11df270d3b35caa842',
    messagingSenderId: '651913327335',
    projectId: 'eazy-order-fcb5b',
    storageBucket: 'eazy-order-fcb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOdf1j1nLnjCiKnV_Cw7cMkJKmEQgmWQ',
    appId: '1:651913327335:ios:65af617393110408caa842',
    messagingSenderId: '651913327335',
    projectId: 'eazy-order-fcb5b',
    storageBucket: 'eazy-order-fcb5b.firebasestorage.app',
    iosBundleId: 'com.app.eazyorder.eazyOrder',
  );
}
